### PR TITLE
Shortcut & UI Improvements

### PR DESCRIPTION
**Pull request by Rene-Roscher**
Hi all,

This pull request includes a series of improvements to the user interface and functionality of the code editor. 

## Shortcuts: 
  - Added a shortcut for `strg+a` to quickly select all of the code content. 
  - Also added a shortcut for `strg+s` to save the changes made to the code. A new reset icon has been added to the interface as well.
  
## Navigation & Style: 
  - A simple modern touch has been added to the navigation and main interface. 
  - Modified the navigation item by adding a dark mode and a transition to improve the overall user experience. 
  
## Dark Mode: 
  - The dark mode coloring has been changed to the `tw-zinc` color to provide a more consistent experience. 

Please let me know if you have any questions or suggestions. 

Best regards,
René Roscher

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks! Can you show some before/after screenshots?

**Comment by Rene-Roscher** [comment]
Sure!

Before:
image
After:
image

**Review by driesvints — CHANGES_REQUESTED** [review]
Some good changes you did. I have to say that I'm not super happy with the new dark colors. The previous one seemed more easy to the eyes to me. Maybe we can revert the colors to the sidebar and make the main code area a bit more closer looking to the sidebar in dark mode?

There also appears to be a vertical scrollbar now which wasn't there before. Can you fix that?

Screenshot 2023-02-15 at 17 37 41

**Comment by Rene-Roscher** [comment]
Sure! I have fixed the overflow and some other misstakes

**Comment by driesvints** [comment]
Did you also revert the changes to the colors like I asked?

**Comment by Rene-Roscher** [comment]
No, the previous colors don't look as good

**Comment by driesvints** [comment]
I think for now, I'd like to keep the previous colors as I personally find them more appealing. We could try to find a better theme for the editor though that matches the dark more colors better. Thanks for your work.

**Pull request closed without merging**
