### PR TITLE
#118 Switch to Vite

### PR DESCRIPTION
**Pull request by thinkverse**
This PR switches over from Laravel Mix to Vite. This PR also removes unused dependencies like `lodash` and `axios` to keep the bundle size down, due to loading all of `highlight.js` the bundle size is ~1000 KB, with gzip compression it's ~290 KB. Similar to the size Webpack produces, but slightly larger initial size. With the unused dependencies bundled I saw a build size of ~1025 KB and ~310 KB with gzip.

Solved the issue I mentioned about line numbers in https://github.com/laravelio/paste.laravel.io/issues/118 by moving the `hljs` import to the `bootstrap.js` file and then importing that into `app.js`, which fixes the issue of the line numbers plugin not finding `hljs` on the window object.

Looking forward to the review. 👍

Closes https://github.com/laravelio/paste.laravel.io/issues/118

### CODE REVIEW

**Comment by driesvints** [comment]
Thanks @thinkverse! Bit short on time now but will give this a go soon.

**Comment by driesvints** [comment]
I can't get the CSS to render. I keep on running into this with every project I migrate to Vite. Do you know what I need to do here?

Screenshot 2022-09-07 at 14 28 00

**Comment by thinkverse** [comment]
> I can't get the CSS to render

I've never had issues running `npm run dev` or `npm run build` and loading Vite assets with Valet or artisan serve. Are you using Sail or Docker? Could be that the port for Vite's dev server isn't open if it runs `dev`? 🤔

**Comment by driesvints** [comment]
Just `artisan server`.

**Comment by thinkverse** [comment]
I just run the npm scripts in another terminal, I never had issues with that before. Is it a CORS issue, or does the browser block assets from different origins?

[How I run Paste with artisan serve](https://www.youtube.com/watch?v=NaavSjCScnU)[^1].

[^1]: https://www.youtube.com/watch?v=NaavSjCScnU

**Comment by thinkverse** [comment]
@driesvints Looking at it again though, it seems the `@vite` directive isn't being interpreted by the Blade compiler since it prints out `@vite([...])`. Did you run `composer install` to install the updated dependencies?

**Comment by thinkverse** [comment]
Yeah, I updated `composer.json` to use `"laravel/framework": "^9.19"`, which is where the Vite directive was added[^1]. And `composer.lock` was updated using `composer update --lock` and that locked Laravel to `v9.27.0`. 🤔

[^1]: Added Vite - https://github.com/laravel/framework/releases/tag/v9.19.0

**Comment by driesvints** [comment]
It suddenly works for me 🤷‍♂️ 

Anyway, very much appreciated @thinkverse, thank you!

**Comment by thinkverse** [comment]
> It suddenly works for me 🤷‍♂️

Computer magic. 🧙‍♂️

**Comment by driesvints** [comment]
I now have issues deploying this... can't figure out what's wrong...

```

> @ build /home/forge/paste.laravel.io/releases/20220908071709
> vite build

sh: 1: vite: not found
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! @ build: `vite build`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/forge/.npm/_logs/2022-09-08T07_17_32_919Z-debug.log
```

**Comment by driesvints** [comment]
Seems like vite itself was missing as a dependency. No idea how I ever got it to build locally 😅

**Comment by thinkverse** [comment]
You know what. I've cracked it, `laravel-vite-plugin` has Vite as a [development dependency](https://github.com/laravel/vite-plugin/blob/8afffba4be8b3a2fac2a5a6de470382282f1529f/package.json#L37) so it'll be installed locally, but if install for production those won't be included, and since I forgot to add Vite as a dependency it was missing on the server and not locally. 🙂

**Comment by driesvints** [comment]
Thanks for checking that 👍

**Pull request merged**
